### ISSUE TITLE
Using an Arduino Leonardo as a dummy Temperature Module

### ISSUE THREAD

**Issue by samm-igt** [OpenTrons/opentrons-modules#447]
I'm trying to use an Arduino Leonardo as a dummy GEN2 Temperature Module (so I can run protocols that require a Temp Module on a real OT-2 for development).

I can't get the OT-2 to recognise the Leonardo as a Temp Module.

I'm using the firmware at: arduino-modules/temp-deck/temp-deck-arduino

So far I've tried:
- Writing serial and model info to the Leonardo's EEPROM
- Hard defining `TD_FW_VERSION` as `"v2.1.0"`
- Flashing the Leonardo firmware directly with an Atmel-ICE via ISP to remove the Arduino bootloader (to hopefully prevent any connection delay issues)
- Making `float Thermistor::temperature()` always return `20.0` to avoid false overheating errors

When accessing both the real Temp Module and the Leonardo via a serial monitor I get identical responses from both, e.g.:

    serial:TDV21P20230814C02 model:temp_deck_v21 version:v2.1.0
    ok
    ok
    T:none C:19.927
    ok
    ok

but the Leonardo is still not recognised by the OT-2.

Is there any other obvious reason why the Leonardo would be seen differently to the Temp Module by the OT-2?

**Comment by fsinapi** [comment]
Hi, thanks for the detailed question! The most likely reason your OT-2 isn't recognizing the Arduino is because of the USB Product and Vendor ID. The OT-2 maps serial devices connected over USB to different module types by matching the PID and VID of the device, so if there is a mismatch then the robot will not recognize a module. 

If you build the firmware with our CMake build system, it will use the values in [this file](https://github.com/Opentrons/opentrons-modules/blob/edge/arduino-modules/arduino-board-files/opentrons-1.3.0/boards.txt#L21) to configure the VID and PID that the firmware uses. If you're using something like the Arduino IDE to build the firmware for  your Arduino, there should be an option to configure the VID and PID to match what the OT-2 expects.

**Comment by samm-igt** [comment]
Thanks, didn't think of that! That's fixed it.

**Comment by fsinapi** [comment]
Great, glad that worked! I'll mark this issue as closed but feel free to follow up if you have any more questions.
